spring.application.name=evento-api
server.port=${SERVER_PORT:8084}

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:eventos}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate

# Swagger
springdoc.api-docs.path=/documentacao
springdoc.swagger-ui.path=/documentacao.html

# Feign
servicos.usuarios.url=http://localhost:8082/api/usuarios
servicos.locais.url=http://localhost:8083/api/locais
servicos.inscricao.url=http://localhost:8085/api/inscricoes
servicos.eventos.url=http://localhost:8084/api/eventos

logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG


#MOCK
spring.profiles.active=local

# RabbitMQ Local
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
spring.rabbitmq.virtual-host=/

broker.queue.evento.atualizar=evento.att.comunicacoes

# APIs
api.usuario.list-url=${API_USUARIO_LIST_URL:http://localhost:8082/api/usuarios}

# Security
security.token.secret=${JWT_SECRET:eventos}
security.token.expiration-time-in-minutes=${JWT_EXPIRATION_IN_MINUTES:60}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Health
management.endpoints.web.exposure.include=health,info,prometheus

# Logging
loki.url=${LOKI_URL:http://localhost:3100/loki/api/v1/push}