spring.application.name=evento
server.port=${SERVER_PORT:8084}

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:eventos}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate

# Swagger
springdoc.api-docs.path=/documentacao
springdoc.swagger-ui.path=/documentacao.html

# Feign
servicos.usuarios.url=http://localhost:8081/api/usuarios
servicos.locais.url=http://localhost:8082/api/locais
servicos.inscricao.url=http://localhost:8083/api/inscricoes
servicos.eventos.url=http://localhost:8084/api/eventos

#MOCK
spring.profiles.active=mock

#RABBITMQ
spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=mgqgopkf
spring.rabbitmq.password=3wgMYHaFSiLavHTKPXKMQtL0PusTD8M7
spring.rabbitmq.virtual-host=mgqgopkf
spring.rabbitmq.ssl.enabled=false

broker.queue.evento.atualizar=evento.att.comunicacoes

# Security
security.token.secret=${JWT_SECRET:eventos}
security.token.expiration-time-in-minutes=${JWT_EXPIRATION_IN_MINUTES:60}