spring.application.name=comunicacao-api

server.port=${SERVER_PORT:8085}
# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:eventos}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate

# Swagger
springdoc.api-docs.path=/documentacao
springdoc.swagger-ui.path=/documentacao.html

# Mailtrap
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=50ed76491dd022
spring.mail.password=01a5c2e749a741
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#MOCK
spring.profiles.active=mock

#RABBITMQ
spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=mgqgopkf
spring.rabbitmq.password=3wgMYHaFSiLavHTKPXKMQtL0PusTD8M7
spring.rabbitmq.virtual-host=mgqgopkf
spring.rabbitmq.ssl.enabled=false

broker.queue.evento.atualizar=evento.att.comunicacoes

# Feign
servicos.usuarios.url=http://localhost:8083/api/usuarios
servicos.locais.url=http://localhost:8081/api/locais
servicos.inscricao.url=http://localhost:8086/api/inscricoes
servicos.eventos.url=http://localhost:8084/api/eventos

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
