services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: eventos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventos
    ports:
      - "5432:5432"
