services:
  auth-api:
    build:
      context: ./auth/.
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  usuario-api:
    build:
      context: ./usuario/.
      dockerfile: Dockerfile
    container_name: usuario-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  local-api:
    build:
      context: ./local/.
      dockerfile: Dockerfile
    container_name: local-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      API_USUARIO_LIST_URL: http://usuario-api:8080/api/usuarios
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - usuario-api

  evento-api:
    build:
      context: ./evento/.
      dockerfile: Dockerfile
    container_name: evento-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      API_USUARIO_LIST_URL: http://usuario-api:8080/api/usuarios
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - usuario-api
      - rabbitmq

  inscricao-api:
    build:
      context: ./inscricao/.
      dockerfile: Dockerfile
    container_name: inscricao-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      API_USUARIO_LIST_URL: http://usuario-api:8080/api/usuarios
      API_EVENTO_LIST_URL: http://evento-api:8080/api/eventos
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    ports:
      - "8085:8080"
    depends_on:
      - postgres
      - evento-api
      - usuario-api
      - rabbitmq

  comunicacoes-api:
    build:
      context: ./comunicacoes/.
      dockerfile: Dockerfile
    container_name: comunicacoes-api
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    ports:
      - "8086:8080"
    depends_on:
      - postgres
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:17-alpine3.21
    container_name: eventos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventos
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  rabbitmq_data:
