# version: "3.9"
# services:
#   inscricao-db:
#     image: postgres:16
#     container_name: inscricao-db
#     environment:
#       POSTGRES_DB: appdb
#       POSTGRES_USER: app
#       POSTGRES_PASSWORD: app
#       TZ: America/Fortaleza
#     ports:
#       - "5433:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
#       interval: 5s
#       timeout: 3s
#       retries: 10

#   inscricao-service:
#     build: .
#     container_name: inscricao-service
#     depends_on:
#       inscricao-db:
#         condition: service_healthy
#     environment:
#       SERVER_PORT: 8081
#       SPRING_PROFILES_ACTIVE: dev        # habilita Flyway (ver app-dev yaml)
#       SPRING_DATASOURCE_URL: jdbc:postgresql://inscricao-db:5432/appdb
#       SPRING_DATASOURCE_USERNAME: app
#       SPRING_DATASOURCE_PASSWORD: app
#       TZ: America/Fortaleza
#     ports:
#       - "8081:8081"

version: "3.9"
services:
  inscricao-db:
    image: postgres:16
    container_name: inscricao-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      TZ: America/Fortaleza
    ports:
      - "5433:5432"   # expõe 5433 no host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10