spring.application.name=service-discovery

server.port=${SERVER_PORT:8761}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Health
management.endpoints.web.exposure.include=health,info,prometheus

# Logging
loki.url=${LOKI_URL:http://localhost:3100/loki/api/v1/push}