spring.application.name=service-discovery

server.port=${SERVER_PORT:8761}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Health
management.endpoints.web.exposure.include=health