{
 "title": "comunicacao-service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"comunicacao-api\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes{area=\"heap\", job=\"comunicacao-api\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{app=\"comunicacao-api\"} | level =~ \"INFO|WARN|ERROR|FATAL\""
    }
   ]
  }
 ]
}