spring.application.name=auth-api

server.port=${SERVER_PORT:8080}

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:eventos}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=none

# Security
security.token.secret=${JWT_SECRET:eventos}
security.token.expiration-time-in-minutes=${JWT_EXPIRATION_IN_MINUTES:60}

# Swagger
springdoc.api-docs.path=/documentacao
springdoc.swagger-ui.path=/documentacao.html

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Health
management.endpoints.web.exposure.include=health