spring.application.name=auth

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/eventos}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=none

# API
api.security.token.secret=${JWT_SECRET:eventos}
api.security.token.expiration-time-in-minutes=${JWT_EXPIRATION_IN_MINUTES:60}