server:
  port: 8081

spring:
  application.name: inscricao
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate.jdbc.time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: app
    password: app
  flyway:
    enabled: false