server.port=${SERVER_PORT:8085}

spring.application.name=inscricao

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:eventos}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# Security
security.token.secret=${JWT_SECRET:eventos}
security.token.expiration-time-in-minutes=${JWT_EXPIRATION_IN_MINUTES:60}

# APIs
api.usuario.list-url=${API_USUARIO_LIST_URL:http://localhost:8082/api/usuarios}
api.evento.list-url=${API_EVENTO_LIST_URL:http://localhost:8084/api/eventos}

# RabbitMQ Local
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin123}
spring.rabbitmq.virtual-host=/

broker.queue.inscricao.criada=inscricao.criada.comunicacoes
