server:
  port: ${SERVER_PORT:8086}

spring:
  application.name: inscricao
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate.jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/eventos
    username: postgres
    password: postgres
  flyway:
    enabled: false